eflyapp/eflyapp/urls.py
from django.contrib import admin
from django.urls import path,include
#añadido
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')), #implementacion sistema de login
    path("",include("todo.urls")),
    ]

#añadido
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eflyapp/todo/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.ver_vuelos,name="home"),
    path('register/', views.register, name='register'),
    path('ChangePassword/<int:DNI>/', views.ChangePassword, name='changePassword'),
    path("Edit/<int:DNI>", views.Edit, name='Edit'),
    path('logout/',views.exit,name='exit'),
    path('create_admin/', views.create_admin, name='create_admin'),
    path('users/', views.user_list, name='user_list'),
    path('users/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path("AdministrarTarjetas/<int:DNI>",views.AdministrarTarjetas,name="AdministrarTarjetas"),
    path("AddCard/<int:DNI>", views.AddCard, name='AddCard'),
    path('vuelo/create', views.crear_vuelo, name='crear_vuelo'),
    path('AdministrarVuelos/', views.administrarvuelos, name='administrarvuelos'),
    path('vuelo/', views.ver_vuelos, name='ver_vuelos'),
    path('vuelo/<int:vuelo_id>/delete/', views.borrar_vuelo, name='borrar_vuelo'),
    path('vuelo/<int:vuelo_id>/edit/', views.edit_vuelo, name='edit_vuelo'),
    path('vuelo/<int:vuelo_id>/promo/', views.promo_vuelo, name='promo_vuelo'),
    path('vuelo/<int:vuelo_id>/comprar/', views.comprar_vuelo, name='comprar_vuelo'),
    path('compra/<int:compra_id>/asiento/', views.seleccionar_asiento, name='seleccionar_asiento'),
    path('compra/', views.ver_compras, name='ver_compras'),
    path('compra/<int:compra_id>/delete/', views.cancelar_compra, name='cancelar_compra'),
    path('compra/<int:compra_id>/pagar/', views.pagar_compra, name='pagar_compra'),
    path('compra/<int:compra_id>/pay/', views.pay_compra, name='pay_compra'),
    #path('crearvuelo/', views.crearvuelo, name='crearvuelo')
    path("AdministrarTarjetas/<int:DNI>/AddSaldo/", views.AddSaldo, name='AddSaldo'),
    path("administrarcompras/<int:DNI>",views.administrarcompras,name="administrarcompras"),
    path("Noticias/",views.Noticias,name="Noticias"),
]

eflyapp/todo/models.py
from django.db import models
from .choices import *
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime


#Modelo de city-lights
class Address(models.Model):
   country = models.ForeignKey('cities_light.Country', on_delete=models.SET_NULL, null=True, blank=True) 
   city = models.ForeignKey('cities_light.City', on_delete=models.SET_NULL, null=True, blank=True)
   
#Pruebas

class CustomUser(AbstractUser):
    DNI=models.IntegerField(primary_key=True, default=0, validators=[MaxValueValidator(9999999999)])
    saldo=models.IntegerField(default=0)
    fechaNaci=models.DateField(null=True)
    lugarNaci= models.ForeignKey('cities_light.City', on_delete=models.SET_NULL, null=True, blank=True)
    dirFact=models.CharField(max_length=100,null=True)
    sexo=models.CharField(max_length=20,choices=genero,default='N')
    tipoUsuario=models.CharField(max_length=20,null=True)
    email = models.EmailField(unique=True)
    picture=models.ImageField(default='profile_default.png',upload_to='users/')

    
#Tablas BD
class Ciudad(models.Model):
    nombreCiudad=models.CharField(max_length=100)
    pais=models.CharField(max_length=100)
    hora=models.TimeField()

    def __str__(self):
        return self.nombreCiudad

class Vuelo(models.Model):
    CIUDADES_PERMITIDAS = [
        ('Pereira', 'Pereira'),
        ('Bogotá', 'Bogotá'),
        ('Medellín', 'Medellín'),
        ('Cali', 'Cali'),
        ('Cartagena', 'Cartagena'),
        ('Madrid', 'Madrid'),
        ('Londres', 'Londres'),
        ('New York', 'New York'),
        ('Buenos Aires', 'Buenos Aires'),
        ('Miami', 'Miami'),
    ]
    codigo = models.CharField(unique=True, null=True, max_length=10)
    origen = models.CharField(max_length=100, choices=CIUDADES_PERMITIDAS)
    destino = models.CharField(max_length=100, choices=CIUDADES_PERMITIDAS)
    filas=models.IntegerField(default=0)
    asientos_fila=models.IntegerField(default=0)
    precioPrimera=models.IntegerField()
    precioEconomica=models.IntegerField()
    precioPrimeraDesc=models.IntegerField(null=True, validators=[MinValueValidator(0)])
    precioEconomicaDesc=models.IntegerField(null=True, validators=[MinValueValidator(0)])
    fechaSalida=models.CharField(null=True, max_length=20)
    horaSalida=models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(23)],null=True)
    minutoSalida=models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(59)],null=True)
    fechaLlegada=models.CharField(null=True, max_length=20)
    horaLlegada=models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(23)],null=True)
    minutoLlegada=models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(59)],null=True)
    tiempoVuelo = models.CharField(null=True, max_length=20)

    @property
    def calcular_tiempo_vuelo(self):
        # Realiza el cálculo del tiempo de vuelo
        # utilizando los campos existentes en el modelo
        # y devuelve el resultado en el formato deseado
        # Por ejemplo, vamos a asumir que los campos necesarios son 'hora_salida' y 'hora_llegada'
        if self.fechaLlegada and self.fechaLlegada:
            return self.fechaLlegada  # Formato de ejemplo

        return None  # En caso de que los campos necesarios no estén completos

    def save(self, *args, **kwargs):
        # Antes de guardar el objeto Vuelo, actualizamos el campo calculado 'tiempo_vuelo'
        self.tiempo_vuelo = self.calcular_tiempo_vuelo
        super(Vuelo, self).save(*args, **kwargs)

class Compra(models.Model):
    vuelo=models.ForeignKey(Vuelo,on_delete=models.CASCADE, null=True)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    #falta la llave foranea
    asientos_economica=models.IntegerField(default=10)
    asientos_primera=models.IntegerField(default=10)
    precio=models.IntegerField(default=10)
    fecha=models.DateField(auto_now=True)
    estado=models.CharField(null=True,max_length=16, default='sin_selec')

class Mensaje(models.Model):
    #noticiaid
    #usuariondni
    #respuestaA
    fecha=models.DateField(auto_now=True)

class Noticia(models.Model):
    #usuario id
    fecha=models.DateField(auto_now=True)
    texto=models.CharField(max_length=300)

class Tarjeta(models.Model):
    clienteid=models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    tipo=models.CharField(null=False,choices=tipoTarjeta,max_length=16)
    disponible=models.IntegerField(default=200000)
    numero=models.CharField(null=False,max_length=16)
    nombre=models.CharField(null=False,max_length=16)
    cvv=models.CharField(null=False,max_length=3)
    vencimiento=models.DateField()

class Seat(models.Model):
    vuelo=models.ForeignKey(Vuelo,on_delete=models.CASCADE, null=True)
    code=models.CharField(null=False,max_length=4)
    estado=models.CharField(null=False,max_length=20)

class Ticket(models.Model):
    Compraid=models.ForeignKey(Compra,on_delete=models.CASCADE,related_name="compraid")
    Vueloid=models.ForeignKey(Vuelo,on_delete=models.CASCADE,related_name="vueloid")
    nombrePasajero=models.CharField(max_length=50,null=True)
    emailPasajero=models.EmailField(null=True)
    edadPasajero=models.IntegerField(null=True)
    asiento=models.ForeignKey(Seat,on_delete=models.CASCADE, null=True)
    clase=models.CharField(choices=ClaseVuelo,max_length=20)
    EstadoCheckIn=models.CharField(default='No Realizado',max_length=15)


# Create your models here.

eflyapp/todo/templates/todo/AddCard.html
{% extends 'todo/layout.html' %}

{% block content %}

<div class="container" id="container">
	<div class="form-container sign-in-container">
		<div class="p-3 mb-2 bg-warning text-dark" style="text-align: center;">
			<h1>Añadir Tarjeta</h1>
		</div>
		<form method="POST" action="" style="display: flex;justify-content: center;">
			{% csrf_token %}

			<div class="container" id="container" style="text-align: center;">
				
				{{form.as_p}}


				<button type="submit" class="btn btn-warning">Añadir Tarjeta</button>
			</div>

			

		</form>
	</div>		
	
</div>
{% endblock %}

eflyapp/todo/templates/todo/AddSaldo.html
{% extends 'todo/layout.html' %}

{% block content %}
<div class="container">
  <h1>Recargar Saldo</h1>

  <p>Saldo actual: {{ cliente.saldo }}</p>

  <h3>Tarjetas disponibles:</h3>
</div>

{% if tarjetas %}
<div class="container">
  <form method="POST">
    {% csrf_token %}

    

    <label for="tarjeta">Seleccionar tarjeta:</label>

    <select name="tarjeta" id="tarjeta">

      {% for tarjeta in tarjetas %}
        <option value="{{ tarjeta.id }}">{{ tarjeta.numero }}</option>
      {% endfor %}
    </select>

    {{ form.as_p }}
    
    <button type="submit">Recargar</button>
  </form>
</div>
{% else %}
<div class="container">
  <p>No tienes tarjetas enlazadas a tu cuenta. Por favor, agrega una tarjeta antes de recargar el saldo.</p>
  <a href="{% url 'AddCard' DNI%}">Agregar Tarjeta</a>
</div>
{% endif %}
{% endblock content %}

eflyapp/todo/templates/todo/Edit.html
{% extends 'todo/layout.html' %}

{% block content %}
<div id="contenedor-editar" class="container text-center">
    
       
    <div class="wrapper">
        <div class="jumbotron jumbotron-fluid bg-white">
            <div class="p-1 mb-2 bg-warning text-dark" style="text-align: center;">
                <h1>Editar Perfil</h1>
            </div>
        </div>

        <form id ="editar" method="POST" action="" style="display: flex;justify-content: center;">
            {% csrf_token %}
            <div class="p-1 form" style="width: 80%;">
                <div class="form-group">
                    <label>Nombre De Usuario</label>
                    <div class="col-sm-10">
                        {{ form.username }}
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-sm-6">
                        <label>Nombre </label>
                        <div class="col-sm-10">
                        {{ form.first_name }}
                        </div>
                    </div>

                    <div class="form-group col-sm-6">
                        <label>Apellido</label>
                        <div class="col-sm-10">
                        {{ form.last_name }}
                        </div>
                    </div>

                </div>
                
                <div class="row">                    
                    <div class="form-group col-sm-6">
                        <label>Lugar de Nacimiento</label>
                        {{ form.lugarNaci }}
                    </div>
                    
                    <div class="form-group col-sm-6">
                        <label>Sexo </label>
                        {{ form.sexo }}
                    </div>
                </div>

                <div class="form-group">
                    <label>Direccion de Facturacion</label>
                    <div class="col-sm-10">
                    {{ form.dirFact }}
                    </div>
                </div>

                <div class="form-group">
                    <input type="hidden" name="tipoUsuario" maxlength="20" required="" id="id_tipoUsuario" value="cliente">
                </div>
                <div class="form-group" style="justify-content: center;">
                    <button type="submit" class="btn btn-warning">Actualizar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

eflyapp/todo/templates/todo/Noticias.html
{% extends 'todo/layout.html' %}

{% block content %}
<div class="container text-center">
    
    <div class="wrapper">
        <div class="jumbotron jumbotron-fluid bg-white">

            <div class="p-3 mb-2 bg-warning text-dark" style="text-align: center;">
                <h1>Noticias</h1>  
                
            </div>
            
        </div>
        <a class="btn btn-warning btn-block" href="#" role="button">Enviar Mensaje</a>
        
        {% if errors %}
        <div class="alert alert-danger" style="text-align: initial;">
            <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                    <li>Error: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        
        <br>
        <div class="card">
            <div class="card-header">
                Mostrando {{ page.start_index }} - {{ page.end_index }} de {{ page.paginator.count }} resultados
            </div>
            <div class="card-body">
                {% for vuelo in page %}
                    <div class="card" style="width: 42rem;">
                        <div class="card-body">
                            <h5 class="card-title"><span class="badge badge-secondary">{{ vuelo.codigo }}</span> {{ vuelo.origen }} - {{ vuelo.destino }}</h5>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6>Salida</h6>
                                    <i class="fa-solid fa-plane-departure"></i> {{ vuelo.fechaSalida }} {{ vuelo.horaSalida }}:{{ vuelo.minutoSalida }}
                                </div>
                                <div class="col-sm-4">
                                    <h6>Llegada</h6>
                                    <i class="fa-solid fa-plane-arrival"></i> {{ vuelo.fechaLlegada }} {{ vuelo.horaLlegada }}:{{ vuelo.minutoLlegada }}
                                </div>
                                
                            </div>
                            <br>
                            <div class="row">
                                {% load humanize %}
                                <div class="col-sm-4">
                                    <h6>Primera Clase</h6>
                                    {% if vuelo.precioPrimeraDesc %}
                                        <h6><s class="text-secondary">$ {{ vuelo.precioPrimera|intcomma }}</s></h6>
                                        <h5>$ {{ vuelo.precioPrimeraDesc|intcomma }}</h5>
                                    {% else %}
                                    <h6>$ {{ vuelo.precioPrimera|intcomma }}</h6>
                                    {% endif %}
                                </div>
                                <div class="col-sm-4">
                                    <h6>Económica</h6>
                                    {% if vuelo.precioEconomicaDesc %}
                                        <h6><s class="text-secondary">$ {{ vuelo.precioEconomica|intcomma }}</s></h6>
                                        <h5>$ {{ vuelo.precioEconomicaDesc|intcomma }}</h5>
                                    {% else %}
                                    <h6>$ {{ vuelo.precioEconomica|intcomma }}</h6>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                {% endfor %}
                <div class="row">
                <div class="col">
                    <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if page.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a></li>
                                {% endif %}
                                <li class="page-item"><a class="page-link" href="#">Página {{ page.number }} de {{ page.paginator.num_pages }}</a></li>
                                {% if page.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}"><span aria-hidden="true">&raquo;</span></a></li>
                                {% endif %}
                            </ul>
                    </nav>  
                </div>
                </div>
                
            </div>
        </div>              
    </div>
</div>
{% endblock %}

eflyapp/todo/templates/todo/changePassword.html
{% extends 'todo/layout.html' %}

{% block content %}

<div class="container" id="container">
	<div class="form-container sign-in-container">
		<form method="POST" action="{% url 'changePassword' user.DNI%}">
			{% csrf_token %}

			<div class="container" id="container" style="text-align: center;">
				<div class="p-3 mb-2 bg-warning text-dark">
					<h2>Cambiar contraseña</h2>
				</div>
				{{form.as_p}}
				
				<a class="btn btn-warning btn-sm"  href="{% url 'home' %}">cambiar contraseña</a>
			</div>

		</form>
	</div>		
	
</div>
{% endblock %}

eflyapp/todo/templates/todo/create_admin.html
{%extends 'todo/layout.html' %}

    {% block content %}
    <div class="container text-center">
        
        <div class="wrapper">
            <div class="jumbotron jumbotron-fluid bg-white p-1">
                <div class="p-3 mb-2 bg-warning text-dark" style="text-align: center;">
                    <h1>Crear Administrador</h1>
                </div>
            </div>
            
            {% if errors %}
            <div class="alert alert-danger" style="text-align: initial;">
                <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        <li>Error en {{ field }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <form method="POST" action="" style="display: flex;justify-content: center;">
                {% csrf_token %}
                <div class="form" style="width: 80%;">
                    <div class="form-group">
                        <label>Nombre De Usuario</label>
                        <div class="col-sm-10">
                            {{ form.username }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label>Nombre </label>
                            <div class="col-sm-10">
                            {{ form.first_name }}
                            </div>
                        </div>
    
                        <div class="form-group col-sm-6">
                            <label>Apellido</label>
                            <div class="col-sm-10">
                            {{ form.last_name }}
                            </div>
                        </div>

                    </div>

                    <div class="form-group">
                        <label>Correo</label>
                        <div class="col-sm-10">
                        {{ form.email }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label>DNI</label>
                        <div class="col-sm-10">
                        {{ form.DNI }}
                        </div>
                    </div>
                    {% load widget_tweaks %}
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label>Contraseña</label>
                            <div class="col-sm-10">
                            {{ form.password1|add_class:"form-control"  }}
                            </div>
                        </div>
                        <div class="form-group col-sm-6">
                            <label>Confirmar Contraseña</label>
                            <div class="col-sm-10">
                            {{ form.password2|add_class:"form-control" }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="hidden" name="tipoUsuario" maxlength="20" required="" id="id_tipoUsuario" value="admin">
                    </div>

                    <div class="form-group" style="justify-content: center;">
                        <button type="submit" class="btn btn-warning">Crear</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

eflyapp/todo/templates/todo/edit_vuelo.html
{%extends '../todo/layout.html' %}

    {% block content %}
    <div class="container text-center">
        
        <div class="wrapper">
            <div class="jumbotron jumbotron-fluid bg-white">
                <div class="p-3 mb-2 bg-warning text-dark" style="text-align: center;">
                    <h1>Editar Vuelo</h1>
                </div>
            </div>
            {% if errors %}
            <div class="alert alert-danger" style="text-align: initial;">
                <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        <li>Error: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            <form method="POST" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-4">
                        <div>
                            <label for="codigo">Código: </label>
                        </div>
                        <div>
                            <h4><span class="badge badge-secondary">{{ vuelo.codigo }}</span></h4>
                        </div>
                    </div>
                    <div class="form-group col-sm-6">
                        <div class="row">
                            <div class="col-sm-4">
                                {% load custom_filters %}
                                <h4><span class="badge badge-warning">Asientos: {{ vuelo.filas|multiply:vuelo.asientos_fila }}(1A-{{ vuelo.filas }}{{ vuelo.asientos_fila|to_letter }})</span></h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-5">
                        <div>
                            <label>Origen: </label>
                        </div>
                        <div>
                            {{ form.origen }}
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label>Fecha Salida: </label>
                        {{ form.fechaSalida }}
                        <script>
                            $('#id_fechaSalida').datepicker({
                                format: "dd-mm-yy",
                                startView: 2,
                                language: "es"
                            });
                        </script>  
                    </div>
                    <div class="form-group col-sm-2">
                        <div>
                            <label>Hora: </label>
                        </div>
                        <div>
                            {{ form.horaSalida }}
                        </div>
                    </div>
                    <div class="form-group col-sm-2">
                        <div>
                            <label>:</label>
                        </div>
                        <div>
                            {{ form.minutoSalida }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-5">
                        <div>
                            <label>Destino: </label>
                        </div>
                        <div>
                            {{ form.destino }}
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label>Fecha Llegada: </label>
                        {{ form.fechaLlegada }}
                        <script>
                            $('#id_fechaLlegada').datepicker({
                                format: "dd-mm-yy",
                                startView: 2,
                                language: "es"
                            });
                        </script>  
                    </div>
                    <div class="form-group col-sm-2">
                        <div>
                            <label>Hora: </label>
                        </div>
                        <div>
                            {{ form.horaLlegada }}
                        </div>
                    </div>
                    <div class="form-group col-sm-2">
                        <div>
                            <label>:</label>
                        </div>
                        <div>
                            {{ form.minutoLlegada }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        <label>Precio Primera Clase: </label>
                        {{ form.precioPrimera }}
                    </div>
                    
                    <div class="form-group col-sm-6">
                        <label>Precio Clase Económica: </label>
                        {{ form.precioEconomica }}
                    </div>
                </div>
                    
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-warning">Guardar</button>
                    </div>
                </div>
                <br>
            </form>  
        </div>
    </div>
{% endblock %}

eflyapp/todo/templates/todo/home.html
{%extends 'todo/layout.html' %}

{%block content%}
<style>
  .contenido{
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 10px;
  }
  
  .btnsuperior{
    display: flex;
  }

  .interface {
    display: flex;
    flex: 100%;
    padding: 1px;
    margin: 1rem;
    flex-grow: 1;
    flex-shrink: 1;
  }
</style>
<!--
<div class="container-fluid bg-warning text-dark d-flex justify-content-center" style="border: 1px solid black; margin-bottom: 10px;">
  {% if request.user.is_authenticated %}
    {% if request.user.tipoUsuario == 'admin' %}
      <h2>Bienvenido {{ user.username | upper }} administrador</h2>
    {%endif%}
    {% if request.user.tipoUsuario == 'cliente' %}
      <h2>Bienvenido {{ user.username | upper }} a E-FLY</h2>
    {%endif%}
  {%else%}
    <h1>Bienvenido a E-FLY</h1>
    
  {%endif%}
</div>
-->
{% if not request.user.is_authenticated %}
  <div class="btnsuperior p-1">
    <a href="#" id="vuelos" class="btn btn-sm btn-warning  btn-outline-dark btn-size" role="button" ><h5>VUELOS</h5></a>
    <a id="checkin" class="btn btn-sm btn-warning  btn-outline-dark btn-size" role="button" href="#"><h5>CHECK-IN</h5></a>
  </div>
{%endif%}

<div class = "interface p-1">
  
  {% if not request.user.tipoUsuario == 'admin'   %}
    {% if not request.user.username == 'root' %}
      <div class="card border-2 shadow my-2" style="border: 1px solid black; display: flex; flex:30%;margin-right: 10px;">
        <h2>SECCION DE NOTICIAS</h2>
      </div>
    {%endif%}
  {%endif%}
  
  {% if not request.user.is_authenticated %}
    <div class="card border-2 shadow my-2" style="border: 1px solid black; display: flex; flex:70%;">
      {% include 'todo/ver_vuelos.html' %}
    </div>
    
  {%endif%}
</div>


<div class="container text-center">
<table class="table table-warning">
    <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

{% endblock %}

eflyapp/todo/templates/todo/promo_vuelo.html
{% extends 'todo/layout.html' %}
    {% block content %}
    <div class="container text-center">
        
        <div class="wrapper">
            <div class="jumbotron jumbotron-fluid bg-white">
                <div class="p-1 mb-2 bg-warning text-dark" style="text-align: center;">
                    <h1>Añadir Promoción</h1>
                </div>
            </div>
            {% if errors %}
            <div class="alert alert-danger" style="text-align: initial;">
                <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        <li>Error: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            <form method="POST" action="">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><span class="badge badge-secondary">{{ vuelo.codigo }}</span> {{ vuelo.origen }} - {{ vuelo.destino }}</h5>
                        <div class="row">
                            <div class="col-sm-6">
                                <h6>Salida</h6>
                                <i class="fa-solid fa-plane-departure"></i> {{ vuelo.fechaSalida }} {{ vuelo.horaSalida }}:{{ vuelo.minutoSalida }}
                            </div>
                            <div class="col-sm-6">
                                <h6>Llegada</h6>
                                <i class="fa-solid fa-plane-arrival"></i> {{ vuelo.fechaLlegada }} {{ vuelo.horaLlegada }}:{{ vuelo.minutoLlegada }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            {% load humanize %}
                            <div class="col-sm-6">
                                <h6>Primera Clase</h6>
                                <h6>$ {{ vuelo.precioPrimera|intcomma }}</h6>
                            </div>
                            <div class="col-sm-6">
                                <h6>Económica</h6>
                                <h6>$ {{ vuelo.precioEconomica|intcomma }}</h6>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <h4>Precios con Descuento</h4>
                <div class="row">
                    <div class="form-group col-sm-6">
                        <label>Precio Primera Clase: </label>
                        {{ form.precioPrimeraDesc }}
                    </div>
                    
                    <div class="form-group col-sm-6">
                        <label>Precio Clase Económica: </label>
                        {{ form.precioEconomicaDesc }}
                    </div>
                </div>
                    
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-warning">Guardar</button>
                    </div>
                </div>
                <br>
            </form>  
        </div>
    </div>
{% endblock %}